### PR TITLE
Resolution of virtual members

### PR DESCRIPTION
**Pull request by magicmoux**
This proposal addresses a solution solution to my comment on issue #113

The changes also includes other features: 
- the decompilation of Expression.xxx calls into their lambda counterpart (useful with EF)
- the translation of Condition(Func<obj,bool>, Func<obj,bool>, Func<obj,bool>) into AndAlso/OrElse expressions

Besides this, I had to upgrade some packages and target networks to be able to check all tests.
Tell me if that is a problem.

### CODE REVIEW

**Comment by hazzik** [comment]
Thanks. I'll take a look.

**Comment by magicmoux** [comment]
Not yet mergeable : 
I found out that there is a problem with virtual members in generic classes due to limitations on  inheritance checking with generic classes

**Comment by magicmoux** [comment]
Ok, seems stable enough (all tests fulfilled on appveyor) and also with my extended tests for portong an awflully "convoluted" external project.
Please tell me if anything comes to mind.

**Comment by magicmoux** [comment]
Ok, seems stable enough (all tests fulfilled on appveyor) and also with my extended tests for porting an awflully "convoluted" external project.
Please tell me if anything comes to mind.

**Comment by magicmoux** [comment]
Ok, seems stable enough (all tests fulfilled on appveyor) and also with my extended tests for porting an awflully "convoluted" external project.
If issues come up on individual side-projects, it may come from the Processor implementation that seems not yet complete (last commit is an occurence of those).
Please tell me if anything else comes to mind.

**Comment by magicmoux** [comment]
Hi all people,
First, best wishes for this new year.
Still no follow up on this PR ?

**Comment by magicmoux** [comment]
Hi Hazzik and all contributors, sorry to insist but still no review there.
Is there anything planned or should we followers assume this project is dead and move on ?
No offence meant, but just to know where we stand.

**Pull request closed without merging**
