### PR TITLE
Allow selecting abstract member over a TPH hierarchy

### PR DESCRIPTION
**Pull request by jaenyph**
This is an implementation proposal as it concern my comment on issue #76 
It allows constructing an appropriate projection of an abstract member selection based on its children implementations.

### CODE REVIEW

**Comment by jaenyph** [comment]
AppVeyor looks for build.cmd, shouldn't it be build.bat ?

**Comment by jaenyph** [comment]
AppVeyor still broken and need to be fixed

**Comment by jaenyph** [comment]
Hi guys, as I have no feedback concerning this PR, I would like to know your point of view about the feature. If there are some adaptations to make to the code don't hesitate to tell.

**Comment by hazzik** [comment]
Thanks. I've made some changes and integrated this. Sorry it took so long to review your work.

**Pull request merged**
