### PR TITLE
Add support for multiple value assignment using BlockExpression return

### PR DESCRIPTION
**Pull request by mycroes**
These changes implement a solution for #122. After changing the implementation of `Final` I noticed some of the array tests breaking, which I traced back to `InitializeArray` calls being handled incorrectly by DelegateDecompiler. All tests are still passing, so I hope I didn't break anything by adding the `BlockExpression` return.

### CODE REVIEW

**Comment by mycroes** [comment]
I'm starting to question the correctness of my implementation. I think that the bug fixed for InitializeArray should also be done for assignments. That would mean that the Expression.Assign statements would no longer be pushed on the stack (because a property's `set_` method also returns `void`) and that the modification to `Final()` would be moot.

**Comment by mycroes** [comment]
Sorry for my absence on this PR. My discovery of the InitializeArray issue led me to new conclusions. I did the simplest test I could to prove my point:
```csharp
public void MethodToDecompile()
{
    AnotherMethod();
}
```
This decompiles to nothing (well actually, it decompiles to something, but it's not really useful).

Another thing I was thinking about is the fact that the stack should be empty after execution of a method. The fact that my implementation of multiple assignment support was based on items on the stack and was working is just luck based on the deviation of DelegateDecompiler vs actual method invocation.

I guess DelegateDecompiler was never really intended to achieve what I want it to do, but I think it might not require much work to actually support the aforementioned scenario's. I'll take another stab at this later.

**Comment by hazzik** [comment]
That's fine, no need to be apologising. Thanks for heads up.

**Comment by mycroes** [comment]
Closing this for now, not sure if I will find time to
1. Investigate and solve this issue
2. Actually implement it in DelegateDecompiler (vs. a specific solution tailored to my problem)

**Pull request closed without merging**
