### PR TITLE
Support Entity Framework Core 5.0

### PR DESCRIPTION
**Pull request by jbogard**
Targets RC2

### CODE REVIEW

**Comment by jbogard** [comment]
This work caused quite the commotion https://github.com/dotnet/runtime/issues/43736

**Comment by hazzik** [comment]
I'll wait when Appveyor update the VS on their 2019 image.

**Comment by CesarD** [comment]
Seems like I'm not the only one checking this one out.
Looking forward to see EF Core 5.0 support. 
This is the only library I have giving me troubles to finally upgrade to EF Core 5.

**Comment by hazzik** [comment]
Released as `DelegateDecompiler.EntityFrameworkCore5`

**Pull request merged**
