### PR TITLE
Added support for property auto-setter

### PR DESCRIPTION
**Pull request by kdblocher**
I'm using your code for walking a dependency hierarchy and need it for more than just expressions.  The code failed when trying to generate an expression for a property auto-setter, so this is a patch for this.

Looking at the code overall, it looks like you don't have support for statements in general, so I propose a feature branch for that.

### CODE REVIEW

**Comment by hazzik** [comment]
Thanks https://github.com/kdblocher can you please add unit tests for your changes?

**Comment by kdblocher** [comment]
Sure thing

**Comment by hazzik** [comment]
@kdblocher any progress on this?

**Comment by hazzik** [comment]
@kdblocher I really want this issue to be fixed, so did you have any chance to add tests for it?

**Comment by kdblocher** [comment]
Not yet - I tried the easy test route, but things are made difficult because it doesn't appear that your project supports statements whatsoever, which is what an auto-property technically is.  You might want to hold off on merging this in until you can try to add statement support.

**Comment by hazzik** [comment]
Can you show what code you are trying to decompile to expression?

**Comment by hazzik** [comment]
Closing as stale

**Pull request closed without merging**
