### PR TITLE
Fix for #59 (and #39)

### PR DESCRIPTION
**Pull request by daveaglick**

### CODE REVIEW

**Comment by daveaglick** [comment]
WIP - will push a fix if I get one.

**Comment by daveaglick** [comment]
The most recent commit resolves the production problems I was having under Roslyn described in #59. I never could get a simple test for the problem due to my production environment being extremely complicated. The earlier test I added seems unrelated so I've left it in but marked it as ignored.

This also fixes the same exception caused by #39 (which suggests the problem with nullable conversions was more general than just my complicated case). I used that test as my benchmark while working on this. It still fails, but with minor differences as suggested in the ignore description as opposed to the `System.ArgumentException` I was getting.

I haven't merged this because I'd like you to take a look and verify the fix is appropriate first. Thanks!

**Comment by hazzik** [comment]
@daveaglick this does fix #58, but I applied a different fix which uses Expression.Default, instead of null constant.

Also, I'm not sure if I can accept the pull request, as it seems fixes different problem for which we do not have a test.

**Comment by daveaglick** [comment]
I still haven't gotten a chance to review if the recent changes make this PR obsolete. I've been running with a custom build with this code for a while - I'll switch to the most recent "official" build after the holidays and test everything out.

This problem a tough one to test because it only appears to cause a problem in very specific scenarios that, try as I might, I can't seem to reproduce in isolated test classes. Hopefully the issue will have been addressed by one of the other changes and we can move on.

**Comment by daveaglick** [comment]
I finally got a chance to run the latest release version (0.18.1) on our production app. Everything looks good, so to the alternate fix for this problem appears to have at least addressed my own use case. Thanks! I'll close the PR since everything looks good.

**Comment by hazzik** [comment]
Cool, thanks.

**Pull request closed without merging**
